---
sudo: required
dist: xenial

language: python
python:
  - "2.7"
  - "3.5"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.10.2
  - ANSIBLE_VERSION=2.10.1
  - ANSIBLE_VERSION=2.10.0
  - ANSIBLE_VERSION=2.9.14
  - ANSIBLE_VERSION=2.9.13
  - ANSIBLE_VERSION=2.9.12
  - ANSIBLE_VERSION=2.9.11
  - ANSIBLE_VERSION=2.9.10
  - ANSIBLE_VERSION=2.9.9
  - ANSIBLE_VERSION=2.9.8
  - ANSIBLE_VERSION=2.9.7
  - ANSIBLE_VERSION=2.9.6
  - ANSIBLE_VERSION=2.9.5
  - ANSIBLE_VERSION=2.9.4
  - ANSIBLE_VERSION=2.9.3
  - ANSIBLE_VERSION=2.9.2
  - ANSIBLE_VERSION=2.9.1
  - ANSIBLE_VERSION=2.9.0
  - ANSIBLE_VERSION=2.8.16
  - ANSIBLE_VERSION=2.8.15
  - ANSIBLE_VERSION=2.8.14
  - ANSIBLE_VERSION=2.8.13
  - ANSIBLE_VERSION=2.8.12
  - ANSIBLE_VERSION=2.8.11
  - ANSIBLE_VERSION=2.8.10
  - ANSIBLE_VERSION=2.8.9
  - ANSIBLE_VERSION=2.8.8
  - ANSIBLE_VERSION=2.8.7
  - ANSIBLE_VERSION=2.8.6
  - ANSIBLE_VERSION=2.8.5
  - ANSIBLE_VERSION=2.8.4
  - ANSIBLE_VERSION=2.8.3
  - ANSIBLE_VERSION=2.8.2
  - ANSIBLE_VERSION=2.8.1
  - ANSIBLE_VERSION=2.8.0

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

  # Remove ansible
  - sudo apt-get remove --purge --yes ansible

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test.yml -vvvv

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - if [ "$ANSIBLE_VERSION" = "latest" ]; then ansible-lint tests/test.yml; fi

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      secure: "o8zXKg2x4njx8/p6Ya44dJ/qH/71JDyWn6mBZHuo13a0h2oaNk15NyuaVClRezWP30G/NYiZfOqTeKZTSNsi4bQR0PXpI/V1q4Zby+9qlcvHFLMfBvHHIOQFhpDSCGHD1GDXw5ctsC12+oyKNEumIEe53g3vrDpjuojbRPoaY9CNJ+qDlBF657XfjKdDp5Z17BQAtb/+OgsMwG2V6JQldL/VQBxZ/IP+Xr/9SEwcAhxKynED0tA3Oq58NuT4xwUL/D7hVxlpj2HYVg7qY/EBMymtKdNsUEkoTgb/N6tI5iVUl/ir+puNKHL/eqSHkeJ6yBeunE+OkWpZ7MQ11CV3BrDXtkfjrpMWbbTIUy6dOf3OClbf8d6/LSW0aVRDetJZ5U7SUi4/nwgu/DDol0gHZcnDxkyoyAd0JK7E9xJzLbPQLQR0OJC+EgRKCQyxfcWZ9RU8Zx67wSY3rZsWAlbQrUN74FMM5tbK0irUaouYG8kK9T5AuH3RMEEj7zRgYBedymIskZzk/2xj/PPrS5IEYZLijyrZake65+yWg80UZtJoWcogocLdDfs/cl8xWE+fYvM7eAzxstjbWkZiNkS0EaUqpghVZasXHX7ar/CxGP3nfGowTFyDaSSHHOuvORyKGcnefPF1KzY3LtKu3gHpmmHIoih+JawNuRF7ChKACwo="
