# tasks file for ansible
---
- name: install ansible (specific version)
  pip:
    name: ansible
    version: "{{ ansible_ansible_version }}"
  when: "ansible_ansible_version != 'latest'"
  tags: [configuration, ansible, ansible-install]

- name: install ansible (latest version)
  pip:
    name: ansible
    state: "{{ ansible_ansible_version }}"
  when: "ansible_ansible_version == 'latest'"
  tags: [configuration, ansible, ansible-install]
