# tasks file for ansible
---
- name: install dependencies
  apt:
    name: "{{ ansible_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - ansible
    - ansible-install
    - ansible-install-dependencies

- name: install ansible (specific version)
  pip:
    name: ansible
    version: "{{ ansible_ansible_version }}"
    executable: "pip{{ ansible_python_version | string }}"
  when: "ansible_ansible_version != 'latest'"
  tags:
    - configuration
    - ansible
    - ansible-install
    - ansible-install-specific

- name: install ansible (latest version)
  pip:
    name: ansible
    state: "{{ ansible_ansible_version }}"
    executable: "pip{{ ansible_python_version | string }}"
  when: "ansible_ansible_version == 'latest'"
  tags:
    - configuration
    - ansible
    - ansible-install
    - ansible-install-latest
